import type { InvoiceForm } from "./invoice-form/types";
import dayjs from "dayjs";

export const dummyInvoiceData: InvoiceForm = {
  invoiceNumber: "INV-2025-0012",
  vehicleNumber: "JK01 AB 4521",
  date: dayjs().format("YYYY-MM-DD"),

  buyerName: "M/S ABC Wholesale Traders",
  buyerAddress: `Shop No. 14, New Market Complex,
Near Grand Crossing,
Srinagar – 190001, Jammu & Kashmir`,
  buyerGstin: "01ABCDE1234F1Z3",

  items: [
    {
      description: "High-Density Polyethylene Granules (HDPE)",
      hsn: "3901",
      qty: 10,
      unit: "Bags",
      rate: 1250,
    },
    {
      description: "Low-Density Polyethylene Granules (LDPE)",
      hsn: "3902",
      qty: 8,
      unit: "Bags",
      rate: 1180,
    },
    {
      description: "PVC Resin – General Purpose",
      hsn: "3904",
      qty: 12,
      unit: "Bags",
      rate: 1390,
    },
    {
      description: "Polypropylene Random Copolymer (PPR)",
      hsn: "3907",
      qty: 15,
      unit: "Bags",
      rate: 1425,
    },
    {
      description: "Thermoplastic Elastomers (TPE) Compound",
      hsn: "3909",
      qty: 4,
      unit: "Bags",
      rate: 1690,
    },

    // Extra items to force multiple pages:
    {
      description: "Recycled Plastic Scrap – Grade A",
      hsn: "3915",
      qty: 20,
      unit: "Kg",
      rate: 45,
    },
    {
      description: "Reprocessed LDPE Film Grade",
      hsn: "3902",
      qty: 25,
      unit: "Kg",
      rate: 65,
    },
    {
      description: "Plastic Agglomerate Mixed Color",
      hsn: "3915",
      qty: 30,
      unit: "Kg",
      rate: 50,
    },
    {
      description: "Polycarbonate Granules – Transparent",
      hsn: "3907",
      qty: 10,
      unit: "Kg",
      rate: 220,
    },
    {
      description: "Virgin PET Resin",
      hsn: "3907",
      qty: 15,
      unit: "Kg",
      rate: 175,
    },
    {
      description: "Masterbatch Color Additive – Blue",
      hsn: "3206",
      qty: 5,
      unit: "Kg",
      rate: 350,
    },
    {
      description: "Masterbatch Color Additive – Black",
      hsn: "3206",
      qty: 5,
      unit: "Kg",
      rate: 320,
    },
    {
      description: "Masterbatch Color Additive – White",
      hsn: "3206",
      qty: 5,
      unit: "Kg",
      rate: 330,
    },
    {
      description: "Plastic Powder Filler – Calcium Carbonate",
      hsn: "2836",
      qty: 50,
      unit: "Kg",
      rate: 18,
    },
    {
      description: "Anti Moisture Powder Additive",
      hsn: "3802",
      qty: 25,
      unit: "Kg",
      rate: 42,
    },
    {
      description: "Virgin PET Resin",
      hsn: "3907",
      qty: 15,
      unit: "Kg",
      rate: 175,
    },
    {
      description: "Masterbatch Color Additive – Blue",
      hsn: "3206",
      qty: 5,
      unit: "Kg",
      rate: 350,
    },
    {
      description: "Masterbatch Color Additive – Black",
      hsn: "3206",
      qty: 5,
      unit: "Kg",
      rate: 320,
    },
    {
      description: "Masterbatch Color Additive – White",
      hsn: "3206",
      qty: 5,
      unit: "Kg",
      rate: 330,
    },
    {
      description: "Plastic Powder Filler – Calcium Carbonate",
      hsn: "2836",
      qty: 50,
      unit: "Kg",
      rate: 18,
    },
    {
      description: "Anti Moisture Powder Additive",
      hsn: "3802",
      qty: 25,
      unit: "Kg",
      rate: 42,
    },
    {
      description: "Virgin PET Resin",
      hsn: "3907",
      qty: 15,
      unit: "Kg",
      rate: 175,
    },
    {
      description: "Masterbatch Color Additive – Blue",
      hsn: "3206",
      qty: 5,
      unit: "Kg",
      rate: 350,
    },
    {
      description: "Masterbatch Color Additive – Black",
      hsn: "3206",
      qty: 5,
      unit: "Kg",
      rate: 320,
    },
    {
      description: "Masterbatch Color Additive – White",
      hsn: "3206",
      qty: 5,
      unit: "Kg",
      rate: 330,
    },
    {
      description: "Plastic Powder Filler – Calcium Carbonate",
      hsn: "2836",
      qty: 50,
      unit: "Kg",
      rate: 18,
    },
    {
      description: "Anti Moisture Powder Additive",
      hsn: "3802",
      qty: 25,
      unit: "Kg",
      rate: 42,
    },
    {
      description: "Last one",
      hsn: "3802",
      qty: 25,
      unit: "Kg",
      rate: 42,
    },
  ],

  discount: 150,
  cgst: 9,
  sgst: 9,
  igst: 0,

  subtotal: 0, // Will be overwritten by computed totals
  cgstAmount: 0,
  sgstAmount: 0,
  igstAmount: 0,
  total: 0,

  sellerName: "Khaldun Plastic Industries",
  sellerAddress: "28A-SIDCO INDL. COMPLEX SHALLATENG SRINAGAR (J&K)",
  sellerEmail: "kpikashmir@gmail.com",
  sellerPhone: "9419009217",
  sellerGstin: "01BSGPB0427H1ZJ",

  amountInWords: "",
};
